source 'https://rubygems.org'

gem 'jbundler'
gem 'json'
gem 'rack', '~> 1.6.0'
gem 'grape'
gem 'faye'
gem 'puma'

group :development, :test do
  gem 'awesome_print'
  gem 'pry'
  gem 'rspec'
  gem 'rack-test', require: 'rack/test'
  gem 'simplecov', require: false
end
